version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - soul-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=straw_dev

volumes:
  soul-pgdata: